import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Risk Disclaimer | Financial Trading Risks Explained',
  description: 'Read the risk disclaimer for Usman Trades. Trading Forex, Gold, and Bitcoin carries significant financial risk. Understand the limitations of our free educational tools and calculators.',
  alternates: {
    canonical: '/disclaimer',
  },
};

export default function Disclaimer() {
  return (
    <article className="max-w-[720px] mx-auto space-y-8">
      <header className="border-b border-border pb-6">
        <h1 className="text-3xl font-extrabold text-primary mb-2 md:text-4xl">Risk Disclaimer</h1>
        <p className="text-sm text-secondary">Effective Date: January 2026</p>
      </header>

      <section className="space-y-4 text-secondary leading-relaxed">
        <h2 className="text-xl font-bold text-primary">1. Financial Trading High Risk Warning</h2>
        <p>
          Trading Foreign Exchange (Forex), Contracts for Difference (CFDs), physical metals like Gold (XAUUSD), and digital assets like Bitcoin carries a high level of risk and may not be suitable for all investors. Leveraged trading allows you to control a large position with a small capital outlay, which can amplify both profits and losses.
        </p>
        <p>
          Before deciding to trade financial products, you should carefully consider your objectives, financial situation, needs, and level of experience. You could sustain a loss of some or all of your deposited capital and therefore should not trade with capital that you cannot afford to lose.
        </p>
      </section>

      <section className="space-y-4 text-secondary leading-relaxed">
        <h2 className="text-xl font-bold text-primary">2. No Investment Advice</h2>
        <p>
          All content, articles, newsletters, market analysis, mathematical tools, calculations, and formulas provided on Usman Trades are strictly for educational and informational purposes. Nothing on this website constitutes investment, tax, legal, or financial advice.
        </p>
        <p>
          We do not issue trade signals, recommend specific securities, suggest brokerage selections, or guarantee any profit margin. Any technical indicators, order flows, or macro structures analyzed in our blog are historical and should not be treated as a prediction of future price movement.
        </p>
      </section>

      <section className="space-y-4 text-secondary leading-relaxed">
        <h2 className="text-xl font-bold text-primary">3. Calculator Accuracy and Third-Party Links</h2>
        <p>
          While we strive to ensure that all calculations (pip values, risk portions, lot sizes) are mathematically accurate based on industry standards, Usman Trades cannot guarantee the absence of typographical errors, systemic bugs, or dynamic market shifts (e.g., changes in currency pricing or contract specifications). All values generated by the tools are estimates.
        </p>
        <p>
          Our platform may link to third-party resources or informational websites. Usman Trades is not responsible for the content, privacy standards, or technical accuracy of external websites.
        </p>
      </section>

      <section className="bg-surface border border-border p-6 rounded-[4px] text-xs text-muted leading-relaxed">
        <strong>IMPORTANT ADVISORY:</strong> Past performance is not indicative of future results. Financial markets are inherently volatile and unpredictably driven by macroeconomic metrics, interest decisions, and geopolitical events. Never execute a transaction without proper risk management structures.
      </section>
    </article>
  );
}
